export const primaryDark = '#1976D2'
export const primary = '#2196F3'
export const primaryLight = '#90CAF9'
export const white = '#FFF'
export const gray = '#E0E0E0'
export const darkGray = '#B0BEC5'
export const black = '#000'
export const red = '#D32F2F'
